import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css';

import { Suspense } from 'react';
import Loading from './loading';

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
        <Suspense fallback={ <Loading /> }>
          <div className="mx-auto max-w-5xl">{children}</div>
        </Suspense>
      </body>
    </html>
  )
}
